merzlab/QUICK

.github/workflows/mpi.yml
.github/workflows/serial.yml
makein/make.in.mpi

Initial attempt at CI on github
Note, there are failing tests in this; testqk.sh needs to be modified to return non-zero in fail cases. 
May resolve  #1

Initial workflow CI attempt

---

configure
src/cuda/cusolver/quick_cusolver.c
src/main.f90
src/octree/grid_packer.cpp
src/subs/getNum.f90
src/subs/whole.f90

I have updated the build system and several source files to enable support for PGI compilers. We can now compile QUICK as: ./configure {options} pgi

Support for PGI compilers

---

Makefile
configure

Added automatic quick.rc generation from configure script

---

Makefile
configure

Eliminated symlinks in quick-amber installation

---

src/scf.f90

Replaced intrinsic matrix multiplication with DGEMM

---

src/quick_one_electron_integral.f90
src/scf_operator.f90

I have enabled mpi parallelization of 1e integrals. This PR should fix issue #53.

MPI parallel 1e integrals

---

src/modules/quick_cutoff_module.f90
src/modules/quick_molspec_module.f90
test/saved/grad_wat_b3lyp_ccpvdz.out

The enclosed changes should solve issue #60.

Improved point charge information printing

---

Makefile
src/blas/Makefile

Changed libblas to libblas-quick

---

configure
src/modules/quick_timer_module.f90

This PR contains improvements for correct ERI gradient time reporting in debug-time/debug mode. Should fix issue #70.

ERI gradient time reporting fixed

---

configure
src/cuda/mgpu.h

Improvements in this PR should fix issue #69.

Fix for seg fault in multi-GPU version

---

configure
src/quick_one_electron_integral.f90
src/scf.f90
src/subs/Makefile
src/subs/diagmkl.f90

This PR contains fixes for issue #77.

LAPACK/MKL DSYEVD integration

---

configure

This PR contains improvements to enable GCC/10.0 support.

Support for GCC/10.2.0

---

src/basis.f90

fixed NPRIM bug

---

configure

This PR contains an update to configure script to detect toolkits CUDA/11.1 and 11.2. Should fix issue #89.

Fix for issue 89

---

src/cuda/mgpu.h
src/cuda/xc_redistribute.cpp

The changes below eliminates several warnings coming from C++ and CUDA codes.

Some fixes for warnings

---

test/Run.tests.amber

This should fix the test failure in Amber's Jenkins.

Small fix in Run.tests.amber

---

.github/workflows/mpi.yml
.github/workflows/serial.yml

The enclosed changes should fix the current CI failures.

Fix for recent CI failure

---

src/cuda/mgpu.h
src/main.f90
src/modules/quick_mpi_module.f90
tools/runtest

The enclosed changes should fix issue #134. Specifically, ERI workload won't be distributed among GPUs in multi-GPU version unless the number of basis functions is greater than a threshold.

Fix for issue 134

---

src/modules/quick_api_module.f90
src/modules/quick_api_test_module.f90
src/quick_api_test.f90

The enclosed changes in this PR should fix issues related to API reported in #144 and #145.

Fixes for issues 144 & 145

---

src/subs/rdword.f90

Added tab delimiter in the input for https://github.com/merzlab/QUICK/issues/127.

add tab delimiter in input

---

.github/workflows/mpi.yml
.github/workflows/serial.yml

The changes here should fix the current CI failure.

Fix for current CI failure

---

tools/runtest

The minor changes here should fix issue #164.

Fix for issue 164

---

src/cuda/mgpu.h
src/modules/quick_exception_module.f90

I have changed the error message reported in issue #177. Additionally, I have decreased the minimum global memory required for the multi-GPU version (felt lazy to open another branch and a PR for a single character change).

Fix for issue 177

---

src/getMol.f90
src/gradient.f90
src/modules/quick_calculated_module.f90
src/optimize.f90

I have fixed issue #187 in this PR. Specifically, I have enabled reusing density matrix during MD and geometry optimization.

Fix for issue 187

---

src/modules/quick_method_module.f90

I have updated the density matrix cutoff to 10-6. This should fix issue #190. Please merge when CI tests are done.

Fix for issue 190

---

configure
src/modules/Makefile

This PR contains a fix for the issue reported in #204.

Fix for issue 204

---

src/modules/quick_api_module.f90
src/modules/quick_constants_module.f90

The changes in this PR should help to get cew to work properly in QUICK/AMBER QM/MM.

Minor changes required for getting cew to work properly

---

src/modules/quick_optimizer_module.f90

Changes in this PR should fix issue #222. 
**Before:** 
```
ANALYTICAL GRADIENT:
----------------------------------------------------------------------------
VARIBLES    OLD_X            OLD_GRAD        NEW_GRAD          NEW_X
----------------------------------------------------------------------------
1X   **************     0.0000101896    -0.0000000126   **************
1Y   101.8353673562     0.0000154731    -0.0000000636   101.8353673562
1Z   102.9568441768    -0.0000048566     0.0000001124   102.9568441768
2X   **************    -0.0000105794     0.0000000316   **************
2Y   101.0737864551    -0.0000232105    -0.0000000027   101.0737864551
2Z   103.2789255461     0.0000168225     0.0000000504   103.2789255461
3X   **************     0.0000003897    -0.0000000190 …
```

Fix for issue 222

---

src/cuda/gpu.cu
src/cuda/gpu_common.h
src/cuda/gpu_get2e_subs.h
src/cuda/gpu_get2e_subs_grad.h
src/cuda/gpu_oei.cu
src/cuda/gpu_oei.h
src/cuda/gpu_oei_assembler.h
src/cuda/gpu_oei_classes.h
src/cuda/gpu_oei_definitions.h
src/cuda/gpu_oei_grad.h
src/cuda/gpu_oei_grad_assembler.h

I have eliminated register spillage of OEI kernels and made some improvements. Please review and merge.

Improvements to OEI kernels

---

src/cuda/gpu_get2e_subs.h

AWG: remove duplicate code

---

quick-cmake/QUICKCudaConfig.cmake

In this PR, I have updated the maximum supported cuda toolkit version to 11.6.

updated maximum supported cuda toolkit version to 11.6

---

src/modules/quick_cew_module.f90
src/subs/sswder.f90

This routine computes the analytic gradients of the ss dft weights. cew module has been changed to use this routine, but the actual DFT code hasn't been touched.

added getsswanader within subs/sswder.f90

---

configure
src/dftd3/Makefile
src/dlfind/Makefile

In this PR, I have fixed the compile time error reported in issue #243.

Fix for issue 243

---

CMakeLists.txt
src/CMakeLists.txt
src/libxc/CMakeLists.txt
src/libxc/maple2c_device/CMakeLists.txt

This PR contains recent changes made by @vwcruzeiro to CMake files of QUICK inside Ambertools.

Changes made to CMake files of QUICK in AMBER

---

.github/workflows/mpi.yml
.github/workflows/serial.yml

In this PR, I have disabled triggering GitHub actions for changes in README files. Please test and merge.

Disabled CI actions for .md files

---

src/dlfind/dlfind_main_driver.f90
src/modules/quick_method_module.f90

I have added the optimization cycles as given by the user. Previously it was hard coded to 100 cycles. I hope it fixes the problem. Could you please share the input file so that I can run from my end?

Added optimization cycles from the quick_method

---

test/Run.tests.amber

Run longer tests (same as for CUDA)

Fix Amber test script for HIP executables

---

src/basis.f90

In this PR, I have re-enabled the trap for F functions.

Enabled F function trap

---

src/modules/quick_api_module.f90
src/modules/quick_files_module.f90

I have made changes required to export data into molden format through API. The changes to sander are in amber-quick branch of the Amber GitLab repo. Please test and merge.

Molden exporting through API

---

src/getMol.f90
src/modules/quick_exception_module.f90

The error trap implemented here should resolve #330.

Error trap for UHF/UDFT calculations with basis sets containing F functions and CUDA version

---

src/basis.f90
src/modules/quick_basis_module.f90
src/modules/quick_molden_module.f90

The enclosed changes resolve #333. Please check and merge.

Fix for issue 333

---

README.md

This MR updates links in documentation for the QUICK-24.03 release.

Documentation updates for QUICK-24.03 release

---

.github/workflows/build_test_mpi.yml
.github/workflows/build_test_serial.yml
tools/runtest

This PR contains additional enhancements and fixes for the Github CI workflows used for testing.

GitHub Workflow Enhancement Part 2

---

README.md
quick-cmake/quick.rc

This PR contains several small fixes and improvements:
- Update badges for Github CI workflows to only reflect the status of the master branch
- Set shell variables for QUICK library files

GitHub Workflow Enhancement Part 3

---

src/gpu/cuda/gpu.cu
src/gpu/cuda/gpu.h
src/gpu/cuda/mgpu.h
src/gpu/hip/gpu.cu
src/gpu/hip/gpu.h
src/gpu/hip/mgpu.h
src/libxc/CMakeLists.txt
src/libxc/gpu_cleanup.cu
src/libxc/gpu_upload.cu
src/main.f90
src/modules/quick_api_module.f90

This PR backports data structure initialization fixes in PR #361 for the single GPU codepaths to the MPI+GPU codepaths.  Moreover, this PR unifies portions of the GPU and MPI+GPU initialization code to simplify future maintainence.

HIP and MPI+HIP Updates Part 2

---

README.md

This PR fixes the README links for the Github workflow action badges.

Fix Github Workflow Badges

---

README.md

Update read-the-docs version tag in README for QUICK-25.03 release.

Documentation Update for QUICK-25.03 release (read-the-docs version tag)

---

README.md

This PR sets the read-the-docs tag back to latest to trakc bugfixes and updates.

Update QUICK documentation post-release (read-the-docs tag to latest).
