Makefile
README.md
configure

These updates enable installing and uninstalling quick executables in $AMBER_HOME/bin. To install QUICK from AMBER scripts, (assuming serial installation) do the following.
`./configure --serial --amprefix $AMBER_HOME gnu`
`make`
`make aminstall`
To uninstall, simply run `make amuninstall`

updates to install quick executables in AMBER installation directory

---

Makefile
configure

I have made the following changes to configure script. 
1) Removed --amprefix and introduced --amber flag. 
This new flag requires the user to specify AMBER_HOME as --prefix. So one can configure for AMBER compatible QUICK installation as follows.
`./configure --serial --mpi --cuda --cudampi --arch volta --shared --amber --prefix $AMBER_HOME gnu`
The script will verify the $AMBER_HOME by checking if AmberTools directory exist inside the given prefix.
2) Modified Makefiles to eliminate aminstall, amunistall dependency 
After the configuration, the user should run `make` and then `make install` to install executables  and libraries into bin and lib folders in $AMBER_HOME. We will check for the existence of bin and lib directories during `make install`. Uninstallation is done by running …

Updates for AMBER compatible install and uninstall

---

src/modules/quick_scratch_module.f90
src/shell.f90

This PR contains a fix for issue 34. Briefly, few large temporary arrays required for CPU ERI gradient code have been moved from stack memory to heap. Furthermore, the sizes of these arrays are now determined by the maximum number of primitive functions during the runtime.

Bug fix for issue 34

---

src/cuda/gpu.cu
src/octree/gpack_common.h
src/octree/grid_packer.cpp

Turned out that I had hardcoded the cutoff in cuda code. I have fixed it in this PR.

Fixed different number of basis/primitive functions resulting from CPU and GPU OCTAGO versions

---

Makefile

I have enabled moving libblas.so into AMBERHOME/lib during amber compatible quick installation. This should fix issue #50.

Fix for issue #50

---

README.md
configure
src/basis.f90
src/cuda/gpu_get2e_subs.h
src/finalize.f90
src/getMol.f90
src/getMolSad.f90
src/main.f90
src/modules/Makefile
src/modules/quick_api_module.f90
src/modules/quick_exception_module.f90
src/modules/quick_files_module.f90
src/shell.f90
src/subs/Makefile
src/subs/fmt.f90
src/subs/mirp_fmt.cpp
src/subs/mirp_fmt.hpp
src/util/util.fh

This PR contains an error trap to prevent users from using f functions and should fix issue #83. 
I have done this by implementing a new error handling scheme. Specifically, I have added a new module (quick_exception_module.f90, contains a couple of subroutines related to error handling) and a fortran header file (util.fh, contains some macro definitions). 
To handle new exceptions, developers must include util.fh in fortran source file and use quick_exception_module in subroutines. The error code and message must be set in the case statement in print_exception subroutine. The error code must be thrown from an appropriate place of a subroutine and caught using CHECK_ERROR() macro immediately after calling that subroutine. 
Note that exception handling will be disabled in debug/debug-time …

Error trap for f functions

---

src/cuda/gpu_common.h
src/cuda/gpu_type.h

This PR contains a fix for the compile time error reported in issue #87. The problem was caused by usage of `cudaErrorNotMappedAsPointer ` error type which was introduced since CUDA/10.1. This has been fixed by selecting correct error type based on the CUDA toolkit version.

Fix for issue 87

---

src/modules/quick_files_module.f90

I have increased the array sizes related to basis path and used fortran90 intrinsics where appropriate. This should fix issue #93.
```
| TASK STARTS ON: Sun Feb 28 10:21:46 2021
| INPUT FILE :    wat.in
| OUTPUT FILE:    wat.out
| DATE FILE  :    wat.dat
| BASIS SET PATH: /home/mmanathunga/bugfix93/quick_brown_fox_jumped_over_the_lazy_dog_again_again_again_again_again_again_again_again_again_oh_damn_again/basis
@ Read Job And Atom
KEYWORD=HF BASIS=6-31G CUTOFF=1.0E-9 DENSERMS=1.0E-6  ENERGY                                                                                                                                                    
============== JOB CARD =============
METHOD = HATREE FOCK
DIRECT SCF 
SAD INITAL GUESS 
USE DIIS SCF
PRINT ENERGY EVERY CYCLE
MAX SCF CYCLES =    200
MAX …
```

Fix for long BS paths

---

.github/workflows/mpi.yml
.github/workflows/serial.yml
CMakeLists.txt
cmake/ConfigModuleDirs.cmake
quick-cmake/QUICKCudaConfig.cmake
quick-cmake/quick.rc
src/CMakeLists.txt
src/libxc/CMakeLists.txt

This PR adds a couple things I missed in the original
- Fix optimization flags to use O2
- Fix permissions on installed tests
- Remove useless libxc_mpi target
It also fixes some incompatibilities with Amber.

More CMake updates

---

CMakeLists.txt
src/CMakeLists.txt

With these changes, the build of QUICK sander should finally work reliably!  It turns out that since some other changes the MPI modules weren't getting put in the right folder.

Few more CMake fixes

---

src/dft.f90

It turns out that the issue #129 is caused by a sloppy conditional statement in DFT grid generation code. This has been fixed. We have to add more dft grids somewhere down the line. SG1 is not good for Alkali, Alkaline earth and halogens. See the following b3lyp/def2-svp energy comparison of different compounds (covers all elements except HI in current scope) between QUICK and a reference code.
```
AlH3 ref: -243.781735361, quick: -243.781908364 diff: 0.00017300300001465985
BeH2 ref: -15.8603827816, quick: -15.860404278 diff: 2.1496400000486915e-05
BH3 ref: -26.5734175368, quick: -26.573418543 diff: 1.006199997988233e-06
CaCl2 ref: -1593.12904130, quick: -1593.129022946 diff: -1.835399984884134e-05
CH4 ref: -40.4887262332, quick: -40.488727144 diff: 9.108000043056563e-07
H2O ref: …
```

Fix for issue #129

---

src/CMakeLists.txt
src/modules/Makefile
src/modules/quick_input_parser_module.f90
src/modules/quick_method_module.f90

The scientific notation reading issues is fixed for all the keywords in the input file of which the value is supposed to be a double. The users are allowed to use the keywords like `cutoff=1e-9 denserms=1e-8`.

fixed the scientific notation reading issue in input

---

src/modules/quick_input_parser_module.f90
src/modules/quick_method_module.f90

A new input parser is implemented. It allows the users to have spaces on the two sides of the equal sign which maps the keyword to the value like `OPTIMIZE = 5` as in https://github.com/merzlab/QUICK/issues/140. It can also parse the keyword at the end of the input line with no trailing spaces (as required in https://github.com/merzlab/QUICK/issues/142).

new input parser

---

CMakeLists.txt
cmake/AmberCompilerConfig.cmake

Update defaults to match the configure based build system. Implemented in root CMakeLists.txt to prevent that compiler options will be overwritten by Amber build system when building inside of Amber. This will have to be changed in the future to make Quick independent of any Amber compiler settings.
- disable warnings so users don't get shocked
- warnings can be enabled with -DWARNINGS=TRUE
- downgrade frome -O3 to -O2 so we won't have nasty surprises with the release on untested platforms
- remove duplicate -O2 flag
- update version number to 21.03
- disable PGI, CRAY, CLANG as these have not been tested or are not working
This supersedes PR #149 which will be closed.

Update CMake build system compiler flags - attempt 2

---

tools/runtest

The B97-GGA1 test was missing from the runtest script info

Add test to runtest script

---

src/main.f90
src/modules/quick_api_module.f90

This PR contains a fix for issue #172. MPI will be always on if the code is compiled with MPIV preprocessor flag. Note that this is a naive solution to prevent mpi hang ups when executing `quick.MPI/quick.cuda.MPI` with `mpirun -np 1`. In future, we should either remove all `bMPI` conditions from the code or put it in all mpi code paths.

Fix for issue #172

---

CMakeLists.txt

This will keep Run.tests.amber executable

Keep permissions when installing test folder

---

configure
quick-cmake/QUICKCudaConfig.cmake

- Enables CUDA Toolkit 11.1 and 11.2
- Adds SM 8.6 for Cuda > 11.0
- Drops SM 3.0 for Cuda >= 11.0 (also updated in configure script)
- Enables manual selection of multiple QUICK_USER_ARCH flags (e.g. "volta turing")

 Update CUDA configurations in CMake build

---

test/Run.tests.amber

After this fix, Jenkins should ignore any failures in `grad` or `opt` tests if executed with `quick.cuda.MPI`.

Tweaks in the Run.tests.amber script to avoid failures in Amber

---

quick-cmake/QUICKCudaConfig.cmake

In this PR, I have changed the nvcc optimization level in CMake build system to -O2. CUDA and CUDAMPI tests run fine as expected. Please check and merge.

Fix for issue 184

---

README.md
configure
src/modules/quick_method_module.f90

Commit 22349aa14
- changed default SCF convergence to 1e-4
- comments in README.md
- configure support for CUDA 11.3
These changes were mistakes. Undo here.

AWG - fix changes introduced in commit 22349aa14

---

CMake-Options.md
CMakeLists.txt

The f function code produces wrong numbers. Disable it by default.

Disable CUDA f functions in CMake by default

---

src/cuda/gpu_getxc.cu
src/cuda/gpu_getxc.h

In this PR, I have made necessary change to disable numerical grid weight derivatives and enable old analytical implementation.

Rolling back to old anlytical sswder code

---

src/modules/include/gradient.fh

In a previous PR I disabled numerical sswder in device code; but I forgot to do the same in host code. In this PR, I have done this.

Rolling back to old analytical sswder implementation in host code

---

CMakeLists.txt
src/modules/quick_method_module.f90

In this PR, I have updated default values of primitive cutoff and number of scf cycles to start the incremental Fock/KS build. I have also eliminated useless `acutoff` variable from quick_method_module. All tests passed.

Random fixes

---

src/cuda/gpu_get2e_subs_grad.h
src/modules/include/eri_grad.fh
src/modules/quick_method_module.f90

I performed a series of HF/DEF2-SVP gradient tests after fixing the the grad cutoff (after commit #53ebb725ea816f0fdde5676ab258c43423493e5d). Everything looks good (see below).  Note that the comparison is wrt. reference data taken from software X. 
```
2-AminoadipicAcid energy = 7.09e-07, Passed; grad = 5.54e-06, Passed 
AbscisicAcid energy = 7.16e-07, Passed; grad = 5.57e-06, Passed 
Anserine energy = 1.09e-06, Passed; grad = 7.49e-06, Passed 
Asparagine energy = 7.68e-07, Passed; grad = 5.69e-06, Passed 
Carnosine energy = 1.07e-06, Passed; grad = 6.71e-06, Passed 
Citrulline energy = 8.08e-07, Passed; grad = 5.69e-06, Passed 
Glutamine energy = 8.94e-07, Passed; grad = 5.73e-06, Passed 
GuanidinoaceticAcid energy = 6.56e-07, Passed; grad = 5.34e-06, Passed 
HippuricAcid energy = …
```

ERI grad cutoff fix

---

src/cuda/gpu_cew_quad.h

Ive fixed a compile time error that occurs when most recent QUICK is compiled with AMBER with CEW support.

Fix for a QUICK-AMBER compile time error 

---

src/cuda/gpu_lri_subs.h
src/cuda/gpu_lri_subs_grad.h

In this PR I have fixed some incorrect pointer arithmetic in 3 center integral code. This fixes wrong energy and gradients currently observed in CEW tests.

Pointer arithmetic fix in 3 center integral code

---

README.md

I have updated the documentation links in README file from v22.3.0 to latest. We can change this for future releases but keep as latest for the master branch.

Changed the docs version to latest

---

.github/workflows/mpi.yml

The changes in this PR should fix CI test failure reported in issue #271. Please close #272 and delete [Madu86:ci-fix ](https://github.com/Madu86/QUICK/tree/ci-fix) branch after merging.

Fix for GitHub CI test failure

---

src/modules/quick_sad_guess_module.f90
src/modules/quick_scf_module.f90
src/modules/quick_size_module.f90
src/modules/quick_uscf_module.f90

The exit condition `idiis.gt.MAX_DII_CYCLE_TIME*quick_method%maxdiisscf` is 1) redundant in the current implementation and 2) leads to a hard-coded maximum number of SCF iterations (DIIS subspace size times hardcoded number of maximum DIIS iterations). This is dumb, also because `idiis` is always equal `jscf`, hence it is sufficient to check for `jscf` as exit condition to limit the number of SCF iterations.
Here we remove the redundant condition and get rid of unnecessary `MAX_DII_CYCLE_TIME`. The user can choose the number of SCF iterations and size of DIIS subspace. There is no need to limit the number of DIIS cycles.

AWG: Remove redundant hard-coded SCF DIIS exit condition

---

src/modules/quick_api_module.f90
src/quick_api_test.f90

Match API keyword string length to Amber.
Increase from 200 to 256.
Longer is better to prevent truncation e.g. with long libxc functional names etc.

Increase keywd length

---

configure
quick-cmake/QUICKCudaConfig.cmake

This PR updates the build systems for recent CUDA versions (12.3).
Also, build options for injecting compilation flags for developer profiling were added for convenience.
Closes #305, #311.

CUDA build updates

---

src/modules/include/eri.fh

In this PR, I have disabled aoint subroutines which leads to a compile-time error when using the intel compiler tool chain. Please check and merge.

Fix for compile time error that occurs with intel compiler tool chain

---

src/basis.f90
src/cuda/gpu_get2e_getxc_drivers.h
src/cuda/gpu_get2e_grad_ffff.cuh
src/modules/include/gradient.fh
src/modules/quick_oei_module.f90
tools/runtest

The enclosed changes fix the segfault in cEW-enabled QM/MM and OEI gradient timing (resolves #323, resolves #325). There was a bug associated with the flag that indicates the availability of F functions. As a result, OEI potential and gradients were computed on the host and the point charge gradient vector wasn't uploaded to the GPU. This caused the segfault. Please check and merge. I will proceed with other issues when this is merged into the master branch.

Fix for issues 323 and 325

---

src/basis.f90
src/modules/quick_exception_module.f90

I have implemented a trap for F functions if the user tries to run cEW-enabled QM/MM with high angular momentum basis sets. This resolves #329. Please test and merge.

F trap for cEW enabled QM/MM

---

src/cuda/gpu_common.h
src/cuda/gpu_get2e_grad_ffff.cu
src/cuda/gpu_get2e_grad_ffff.cuh

In this PR, I have made changes to CUDA F gradient kernels to support legacy atomic add. Users won't be able to run F kernels on Kepler cards though. This is because we moved device pointers and some constants from constant memory into the shared memory. This improves the performance and the implementation we have in F gradient source files ( https://github.com/merzlab/QUICK/blob/326-support-for-legacy-atomics-in-cuda-f-gradient-kernels/src/cuda/gpu_get2e_grad_ffff.cu#L259-L505, https://github.com/merzlab/QUICK/blob/326-support-for-legacy-atomics-in-cuda-f-gradient-kernels/src/cuda/gpu_get2e_grad_ffff.cuh#L1695-L1730) is my experimental implementation. We should implement some templates, clean this up, and update other OEI/ERI/LRI kernels to use shared memory. Will be very useful for …

Support for legacy atomics in cuda f gradient kernels

---

src/cuda/gpu.cu

The enclosed change should resolve #337. It seems that ifort represent logical true using 255 rather than 1. As a result, when we pass the "is_oshell" flag value from Fortran to C code (https://github.com/merzlab/QUICK/blob/master/src/cuda/gpu.cu#L385-L402), the value in C code was not set properly, and closed shell kernel was invoked for open shell XC calculation (https://github.com/merzlab/QUICK/blob/master/src/cuda/gpu_getxc.cu#L98-L113). Please test and merge.

Fix for issue 337

---

configure
quick-cmake/QUICKCudaConfig.cmake

Temporarily disable support for HIP and MPI+HIP builds.  This will be revisited post next Amber release when the CUDA code stabilizes and can be ported to the HIP code.
Related: #344

Disable support for HIP and MPI+HIP builds

---

CMakeLists.txt

This is a minor update to copy runtest script into Ambertools/src/quick when QUICK is compiled inside AMBER.

Update to CMakeListst.txt

---

src/modules/quick_molspec_module.f90

Support reading as many elements as are defined in quick_constants_module. These are 92 elements. We do not have ECPs so there are not really any basis sets that we can use beyond Kr. However, at least be consistent for the future.
Closes #356

AWG - fix reading heavy elements

---

src/modules/quick_cew_module.f90

file unit dummy argument intent appears to be incorrect, which could result in using an uninitialized value

ioutfile intent in rather than intent out

---

README.md

This MR updates links in documentation for post QUICK-24.03 release (latest version on QUICK-docs/readthedocs).

Documentation updates for post QUICK-24.03 release

---

src/modules/quick_scf_module.f90
src/modules/quick_uscf_module.f90

This update resolves a segmentation fault issue that occurred when running the application on the CPU and attempting to export data to MOLDEN format.

Fixes Segmentation error during  MOLDEN export on CPU run

---

src/CMakeLists.txt

DLFIND_MODULES_SOURCES was defined twice.
Remove duplicate from CMakeLists.txt

AWG: Remove duplicate definition of DLFIND_MODULES_SOURCES

---

.github/workflows/build_test_mpi.yml
.github/workflows/build_test_serial.yml

This PR switches to using the compiler type keywords (GNU, CLANG, etc.) for the build systems in order to automatically set the compiler executables and compilation flags used (and thereby tests the common selections by end users).
The current code does manually set the compiler executables but neglects to set the compilation flags (which is a bug).  This fixes this issue.

Fix Setting Compilation Flags for GitHub CI Workflow Tests

---

src/CMakeLists.txt

This PR fixes setting the Fortran source compiler optimization flags in CMake builds (due to an issue with case-senstive naming with COMPILE_LANAUGE in generator expressions [FORTRAN -> Fortran]).
Credit to @vtripath65 for noticing performance regressions in Fortran sources which led to this fix.

Fixes from AmberTools 2025 Integration Part 2

---

CMakeLists.txt

This PR addresses several issues:
- CMake compiler flags not correctly set for mixed Clang/GCC builds (`-DCOMPILER=CLANG`)
- Fix improper GCC compiler flags being set for recent Apple ARM CPUs (>= M3) for CMake builds due to limitations in upstream Amber/AmberTools CMake target architecture detection

Fixes from AmberTools 2025 Integration Part 3

---

quick-cmake/QUICKCudaConfig.cmake
src/gpu/cuda/gpu.cu
src/gpu/cuda/mgpu.h
src/gpu/hip/gpu.cu
src/gpu/hip/mgpu.h

This PR contains updates for known working (tested) versions of ROCm versions (>= v6.2.1, <= v5.4.2) for HIP and MPI+HIP versions of QUICK.
This was tested on the MI200 series GPUs on the AMD Accelator Cloud (M210 / MI250).

HIP and MPI+HIP Updates Part 3

---

src/gpu/int_lri.h

This PR addresses a build failure reported in #425 in the GPU LRI code with AmberTools when f function support is enabled.
Specifically, the vertical_spdf2 device function was accidentally omitted following the non-LRI & LRI VRR code split (see files `src/gpu/int.h` and `src/gpu/int_lri.h`, respectively).
Code in the PR will also need to be upstreamed to AmberTools 2025 as a point release to push out this fix to users.
Closes #425.

GPU LRI Build Fix with f Function Support

---

src/dlfind/dlf_convergence.f90
src/modules/quick_method_module.f90
src/modules/quick_optimizer_module.f90

Required comma as field separator was missing in some format descriptors for write statements in geometry optimization routines (legacy optimizer, DLFIND, methods module).
This was silently accepted with GCC versions <= 14 but leads to runtime errors with GCC 15.
Fixes errors with GCC 15, which is more strict.

AWG: Bugfix: Add missing comma in write statement field descriptor
